from typing import Protocol
from frayerstore.models.level import Level
from frayerstore.models.level_create import LevelCreate


class LevelRepository(Protocol):
    def get_by_id(self, id: int) -> Level | None: ...
    def get_by_slug(self, slug: str) -> Level | None: ...
    def get_by_name(self, name: str) -> Level | None: ...
    def create(self, data: LevelCreate) -> Level: ...
