from typing import Protocol
from frayerstore.models.subject import Subject


class SubjectRepository(Protocol):
    def get_by_slug(self, slug: str) -> Subject | None: ...
    def get_by_name(self, name: str) -> Subject | None: ...
    def get_by_id(self, id: int) -> Subject | None: ...
    def save(self, subject: Subject) -> Subject: ...
