from typing import Protocol
from frayerstore.models.topic import Topic
from frayerstore.models.topic_create import TopicCreate


class TopicRepository(Protocol):
    def get_by_id(self, id: int) -> Topic | None: ...
    def get_by_slug(self, slug: str) -> Topic | None: ...
    def get_by_name(self, name: str) -> Topic | None: ...
    def create(self, data: TopicCreate) -> Topic: ...
